### ISSUE TITLE
Release 4.7 checklist

### ISSUE THREAD

**Issue by dgrisonnet** [openshift/cluster-monitoring-operator#1007]
# Feature freeze release checklist

## Golang projects and backports

- [x] update downstream backport of [openshift/node_exporter](https://github.com/openshift/node_exporter)
- [x] update downstream backport of [openshift/prometheus](https://github.com/openshift/prometheus)
- [x] update downstream backport of [openshift/alertmanager](https://github.com/openshift/alertmanager)
- [x] update downstream backport of [openshift/thanos](https://github.com/openshift/thanos)
- [x] update downstream backport of [openshift/prometheus-operator](https://github.com/openshift/prometheus-operator)
- [x] update downstream backport of [openshift/kube-state-metrics](https://github.com/openshift/kube-state-metrics)
- [x] update downstream backport of [openshift/kube-rbac-proxy](https://github.com/openshift/kube-rbac-proxy)
- [x] update downstream backport of [openshift/k8s-prometheus-adapter](https://github.com/openshift/k8s-prometheus-adapter)
- [x] update downstream backport of [openshift/grafana](https://github.com/openshift/grafana)
- [x] update downstream backport of [openshift/prom-label-proxy](https://github.com/openshift/prom-label-proxy)
- [x] update downstream backport of [openshift/procfs](https://github.com/openshift/procfs)

## Jsonnet dependencies

- [x] cut new release in [kubernetes-monitoring/kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin)
- [x] cut new release in [thanos-io/kube-thanos](https://github.com/thanos-io/kube-thanos)
- [x] cut new release in [coreos/kube-prometheus](https://github.com/coreos/kube-prometheus)
  - update dependencies before doing release

## Cluster Monitoring Operator

- [x] update and pin jsonnet dependencies in [jsonnet/jsonnetfile.json](https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/jsonnetfile.json).
  - example: https://github.com/openshift/cluster-monitoring-operator/blob/release-4.3/jsonnet/jsonnetfile.json
  - dependencies should be pinned to branches released in previous paragraph
- [x] update golang dependencies by modifying [go.mod](https://github.com/openshift/cluster-monitoring-operator/blob/master/go.mod) file.
  - most important are dependencies on prometheus-operator and kubernetes components

**Comment by dgrisonnet** [comment]
closing out as all the tasks are done
