### ISSUE TITLE
Release 4.9 checklist

### ISSUE THREAD

**Issue by jan--f** [openshift/cluster-monitoring-operator#1320]
# Feature freeze release checklist

## Golang projects and backports

- [x] update downstream backport of [openshift/node_exporter](https://github.com/openshift/node_exporter)
  - [x] bump [openshift/procfs](https://github.com/openshift/procfs) to the version used in the node_exporter's upstream version we want to bump to, including any downstream patch we may have
  - [x] bump [openshift/node_exporter](https://github.com/openshift/node_exporter) to the upstream version replacing the procfs dependency by the downstream repo
- [x] update downstream backport of [openshift/prometheus](https://github.com/openshift/prometheus)
- [x] update downstream backport of [openshift/alertmanager](https://github.com/openshift/alertmanager)
- [x] update downstream backport of [openshift/thanos](https://github.com/openshift/thanos)
- [x] update downstream backport of [openshift/prometheus-operator](https://github.com/openshift/prometheus-operator)
- [x] update downstream backport of [openshift/kube-state-metrics](https://github.com/openshift/kube-state-metrics)
- [x] update downstream backport of [openshift/kube-rbac-proxy](https://github.com/openshift/kube-rbac-proxy)
- [x] update downstream backport of [openshift/k8s-prometheus-adapter](https://github.com/openshift/k8s-prometheus-adapter)
- [x] update downstream backport of [openshift/grafana](https://github.com/openshift/grafana)

## Jsonnet dependencies

- [x] cut new release in [kubernetes-monitoring/kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin)
- [x] cut new release in [thanos-io/kube-thanos](https://github.com/thanos-io/kube-thanos)
- [x] cut new release in [prometheus-operator/kube-prometheus](https://github.com/prometheus-operator/kube-prometheus)
  - update dependencies before doing release

## Cluster Monitoring Operator

- [x] update and pin jsonnet dependencies in [jsonnet/jsonnetfile.json](https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/jsonnetfile.json).
  - example: https://github.com/openshift/cluster-monitoring-operator/blob/release-4.3/jsonnet/jsonnetfile.json
  - dependencies should be pinned to branches released in previous paragraph
  - ensure `jsonnet/version.json` file is tracking up-to-date component versions by running `make versions` and regenerating `assets/` if necessary
- [x] update golang dependencies in [go.mod](https://github.com/openshift/cluster-monitoring-operator/blob/master/go.mod) and [hack/tools/go.mod](https://github.com/openshift/cluster-monitoring-operator/blob/master/hack/tools/go.mod) files.
  - most important are dependencies on prometheus-operator and kubernetes components
  - update the tooling prometheus dependency to be in sync with the main one

**Comment by jan--f** [comment]
update procfs: https://github.com/openshift/procfs/pull/4
