### ISSUE TITLE
Release 4.10 checklist

### ISSUE THREAD

**Issue by simonpasquier** [openshift/cluster-monitoring-operator#1486]
# Feature freeze release checklist

## Golang projects and backports

- [x] update downstream backport of [openshift/node_exporter](https://github.com/openshift/node_exporter)
  - [x] bump [openshift/procfs](https://github.com/openshift/procfs) to the version used in the node_exporter's upstream version we want to bump to, including any downstream patch we may have
  - [x] bump [openshift/node_exporter](https://github.com/openshift/node_exporter) to the upstream version replacing the procfs dependency by the downstream repo
- [x] update downstream backport of [openshift/prometheus](https://github.com/openshift/prometheus)
- [x] update downstream backport of [openshift/alertmanager](https://github.com/openshift/alertmanager)
- [x] update downstream backport of [openshift/thanos](https://github.com/openshift/thanos)
- [x] update downstream backport of [openshift/prometheus-operator](https://github.com/openshift/prometheus-operator)
- [x] update downstream backport of [openshift/kube-state-metrics](https://github.com/openshift/kube-state-metrics)
- [x] update downstream backport of [openshift/kube-rbac-proxy](https://github.com/openshift/kube-rbac-proxy)
- [x] update downstream backport of [openshift/k8s-prometheus-adapter](https://github.com/openshift/k8s-prometheus-adapter)
- [x] update downstream backport of [openshift/grafana](https://github.com/openshift/grafana)

## Jsonnet dependencies

- [x] cut new release in [kubernetes-monitoring/kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin)
- [x] cut new release in [thanos-io/kube-thanos](https://github.com/thanos-io/kube-thanos)
- [x] cut new release in [prometheus-operator/kube-prometheus](https://github.com/prometheus-operator/kube-prometheus)
  - update dependencies before doing release

## Cluster Monitoring Operator

- [x] update and pin jsonnet dependencies in [jsonnet/jsonnetfile.json](https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/jsonnetfile.json).
  - example: https://github.com/openshift/cluster-monitoring-operator/blob/release-4.3/jsonnet/jsonnetfile.json
  - dependencies should be pinned to branches released in previous paragraph
  - ensure `jsonnet/version.json` file is tracking up-to-date component versions by running `make versions` and regenerating `assets/` if necessary
- [x] update golang dependencies in [go.mod](https://github.com/openshift/cluster-monitoring-operator/blob/master/go.mod) and [hack/tools/go.mod](https://github.com/openshift/cluster-monitoring-operator/blob/master/hack/tools/go.mod) files.
  - most important are dependencies on prometheus-operator and kubernetes components
  - update the tooling prometheus dependency to be in sync with the main one

**Comment by arajkumar** [comment]
@simonpasquier IIUC, we can ignore openshift/kube-rbac-proxy as it is already taken care by auth team?

**Comment by arajkumar** [comment]
Thanos update is done https://github.com/openshift/thanos/pull/75

**Comment by arajkumar** [comment]
KSM also have been [bumped to latest](https://github.com/openshift/kube-state-metrics/pull/64), but I guess another important release will be coming over mid of Dec which will be carrying PDB label metrics related fixes. @fpetkovski Do you aware of timeline?

**Comment by fpetkovski** [comment]
We should be releasing KSM 2.3.0 in this sprint because Kubernetes 1.23 is out

**Comment by arajkumar** [comment]
Thanks @fpetkovski. That makes sense.

**Comment by arajkumar** [comment]
@simonpasquier Reg openshift/node_exporter and openshift/procfs. I see that downstream node_exporter uses upstream procfs[1] without any replace statement. Am I missing something here?

[1] https://github.com/openshift/node_exporter/blob/master/go.mod#L19

**Comment by arajkumar** [comment]
[prom_label_proxy](https://github.com/openshift/prom-label-proxy) is missing from the list.

**Comment by simonpasquier** [comment]
> Reg openshift/node_exporter and openshift/procfs. I see that downstream node_exporter uses upstream procfs[1] without any replace statement. Am I missing something here?

We had to use openshift/procfs a while back because we had to backport a patch there (IIRC we couldn't use the upstream procfs because it wouldn't compile with our downstream node_exporter without massive changes). TL;DR: the downstream fork still exists but isn't used anymore. It might be useful in the future but in any case, it should be used for z stream releases so it's not useful to have it in the release checklist.
