### ISSUE TITLE
Release 4.12 Checklist 

### ISSUE THREAD

**Issue by raptorsun** [openshift/cluster-monitoring-operator#1807]
# Feature freeze release checklist

## Golang projects and backports
Projects should already be up-to-date thanks to the monitoring bot but worth verifying.

- [x] update downstream backport of [openshift/node_exporter](https://github.com/openshift/node_exporter)
- [x] update downstream backport of [openshift/prometheus](https://github.com/openshift/prometheus)
- [x] update downstream backport of [openshift/alertmanager](https://github.com/openshift/alertmanager)
- [x] update downstream backport of [openshift/thanos](https://github.com/openshift/thanos)
- [x] update downstream backport of [openshift/prometheus-operator](https://github.com/openshift/prometheus-operator)
- [x] update downstream backport of [openshift/kube-state-metrics](https://github.com/openshift/kube-state-metrics)
- [x] update downstream backport of [openshift/kube-rbac-proxy](https://github.com/openshift/kube-rbac-proxy)
- [x] update downstream backport of [openshift/k8s-prometheus-adapter](https://github.com/openshift/k8s-prometheus-adapter)

## Jsonnet dependencies

- [x] cut new release in [kubernetes-monitoring/kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin)
  - [x] [PR for cutting release-0.12](https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/803)
- [x] cut new release in [thanos-io/kube-thanos](https://github.com/thanos-io/kube-thanos): already cut 0.28.1 by [this PR](https://github.com/thanos-io/kube-thanos/pull/287)
- [x] cut new release in [prometheus-operator/kube-prometheus](https://github.com/prometheus-operator/kube-prometheus)
  - update dependencies before doing the release
  - kubernetes-mixin  [PR for cutting release-0.12](https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/803) is ready
  - [PR cutting release-0.12](https://github.com/prometheus-operator/kube-prometheus/pull/1919)

## Cluster Monitoring Operator

PR updating jsonnet dependencies and golang dependencies: https://github.com/openshift/cluster-monitoring-operator/pull/1808
- [x] update and pin jsonnet dependencies in [jsonnet/jsonnetfile.json](https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/jsonnetfile.json).
  - example: https://github.com/openshift/cluster-monitoring-operator/blob/release-4.3/jsonnet/jsonnetfile.json
  - dependencies should be pinned to branches released in the previous paragraph
  - ensure `jsonnet/version.json` file is tracking up-to-date component versions by running `make versions` and regenerating `assets/` if necessary
- [x] update golang dependencies in [go.mod](https://github.com/openshift/cluster-monitoring-operator/blob/master/go.mod) and [hack/tools/go.mod](https://github.com/openshift/cluster-monitoring-operator/blob/master/hack/tools/go.mod) files.
  - most important are dependencies on Prometheus-Operator and Kubernetes components
  - update the tooling Prometheus dependency to be in sync with the main one

**Comment by jan--f** [comment]
@raptorsun Can you update and close this please or is there anything missing?

**Comment by raptorsun** [comment]
All the tasks are complete. The issue is closed.
