### ISSUE TITLE
Release 4.13 Checklist

### ISSUE THREAD

**Issue by jan--f** [openshift/cluster-monitoring-operator#1901]
# Feature freeze release checklist

## Golang projects and backports

- [x] update downstream backport of [openshift/node_exporter](https://github.com/openshift/node_exporter)
- [x] update downstream backport of [openshift/prometheus](https://github.com/openshift/prometheus)
- [x] update downstream backport of [openshift/alertmanager](https://github.com/openshift/alertmanager)
- [x] update downstream backport of [openshift/thanos](https://github.com/openshift/thanos)
- [x] update downstream backport of [openshift/prometheus-operator](https://github.com/openshift/prometheus-operator)
- [x] update downstream backport of [openshift/kube-state-metrics](https://github.com/openshift/kube-state-metrics)
- [x] update downstream backport of [openshift/kube-rbac-proxy](https://github.com/openshift/kube-rbac-proxy)
- [x] update downstream backport of [openshift/k8s-prometheus-adapter](https://github.com/openshift/k8s-prometheus-adapter)

## Jsonnet dependencies

- [ ] ~cut new release in [kubernetes-monitoring/kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin)~
- [ ] ~cut new release in [thanos-io/kube-thanos](https://github.com/thanos-io/kube-thanos)~
- [ ] ~cut new release in [prometheus-operator/kube-prometheus](https://github.com/prometheus-operator/kube-prometheus)~

## Cluster Monitoring Operator

- [ ] update and pin jsonnet dependencies in [jsonnet/jsonnetfile.json](https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/jsonnetfile.json).
  - example: https://github.com/openshift/cluster-monitoring-operator/blob/release-4.3/jsonnet/jsonnetfile.json
  - dependencies should be pinned to branches released in previous paragraph
  - ensure `jsonnet/version.json` file is tracking up-to-date component versions by running `make versions` and regenerating `assets/` if necessary
- [ ] update golang dependencies in [go.mod](https://github.com/openshift/cluster-monitoring-operator/blob/master/go.mod) and [hack/tools/go.mod](https://github.com/openshift/cluster-monitoring-operator/blob/master/hack/tools/go.mod) files.
  - most important are dependencies on prometheus-operator and kubernetes components
  - update the tooling prometheus dependency to be in sync with the main one

**Comment by jan--f** [comment]
I checked off the golang updates since syncbot keeps those updated for us.

I propose to forego the releases of our jsonnet upstreams. This always takes a fair amount of effort and time and we can simply ping a desired commit for our release as well.
