### ISSUE TITLE
Release 4.5 checklist

### ISSUE THREAD

**Issue by lilic** [openshift/cluster-monitoring-operator#756]
# Feature freeze release checklist

## Golang projects and backports
---
Complete:
- [x] update downstream backport of [openshift/k8s-prometheus-adapter](https://github.com/openshift/k8s-prometheus-adapter)
https://github.com/openshift/k8s-prometheus-adapter/pull/25 ?
- [x] ~cut new upstream~ [prometheus-operator](https://github.com/coreos/prometheus-operator) WIP: bring in the 0.38.1 release to bring in bug fixes
- [x] update downstream backport of [openshift/kube-rbac-proxy](https://github.com/openshift/kube-rbac-proxy)
https://github.com/openshift/kube-rbac-proxy/pull/22
- [x] update downstream backport of [openshift/prometheus-operator](https://github.com/openshift/prometheus-operator)
- [x] update downstream backport of [openshift/thanos](https://github.com/openshift/thanos)
https://github.com/openshift/thanos/pull/25
- [x] update downstream backport of [openshift/node_exporter](https://github.com/openshift/node_exporter) - no new releases only rc-0
- [x] update downstream backport of [openshift/prometheus](https://github.com/openshift/prometheus) - we decided against this for this release due to known performance problems 
- [x] update downstream backport of [openshift/alertmanager](https://github.com/openshift/alertmanager) - no new releases
- [x] update downstream backport of [openshift/kube-state-metrics](https://github.com/openshift/kube-state-metrics) - we have latest release
- [x] update downstream backport of [openshift/grafana](https://github.com/openshift/grafana)
https://github.com/openshift/grafana/pull/31 We decided against this.

## Jsonnet dependencies

- [x] cut new release in [kubernetes-monitoring/kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin)
- [x] cut new release in [thanos-io/kube-thanos](https://github.com/thanos-io/kube-thanos)
https://github.com/thanos-io/kube-thanos/pull/113
https://github.com/thanos-io/kube-thanos/pull/114
- [x] cut new release in [coreos/kube-prometheus](https://github.com/coreos/kube-prometheus)
  - update dependencies before doing release
 https://github.com/coreos/kube-prometheus/pull/496

## Cluster Monitoring Operator

- [x] update and pin jsonnet dependencies in [jsonnet/jsonnetfile.json](https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/jsonnetfile.json).
  - example: https://github.com/openshift/cluster-monitoring-operator/blob/release-4.3/jsonnet/jsonnetfile.json
https://github.com/openshift/cluster-monitoring-operator/pull/760
  - dependencies should be pinned to branches released in previous paragraph
- [x] update golang dependencies by modifying [go.mod](https://github.com/openshift/cluster-monitoring-operator/blob/master/go.mod) file.
  - most important are dependencies on prometheus-operator and kubernetes components
we are not bumping k8s this time around

**Comment by paulfantom** [comment]
> cut new upstream prometheus-operator release

I think we need to adjust this entry due to newly introduced release cadence in prometheus-operator project

/cc @simonpasquier @s-urbaniak

**Comment by lilic** [comment]
Agreed, feel free to open PR to edit this. 👍

**Comment by lilic** [comment]
Once the last PR is merged we can close this I guess.
