### ISSUE TITLE
Release 4.6 checklist

### ISSUE THREAD

**Issue by simonpasquier** [openshift/cluster-monitoring-operator#847]
# Feature freeze release checklist

## Golang projects and backports

- [X] update downstream backport of [openshift/node_exporter](https://github.com/openshift/node_exporter), v0.18.2 -> v1.0.1 https://github.com/openshift/node_exporter/pull/62
- [x] update downstream backport of [openshift/prometheus](https://github.com/openshift/prometheus), v2.15.2 -> v2.20.0 https://github.com/openshift/prometheus/pull/52 
- [X] update downstream backport of [openshift/alertmanager](https://github.com/openshift/alertmanager), v0.20.0 -> v0.21.0 https://github.com/openshift/prometheus-alertmanager/pull/34
- [x] update downstream backport of [openshift/thanos](https://github.com/openshift/thanos), v0.12.2 -> v0.14.0 (+ 2 patches) https://github.com/openshift/thanos/pull/32
- [x] update downstream backport of [openshift/prometheus-operator](https://github.com/openshift/prometheus-operator), v0.38.1 -> v0.40.0 https://github.com/openshift/prometheus-operator/pull/80
- [x] update downstream backport of [openshift/kube-state-metrics](https://github.com/openshift/kube-state-metrics), tracked in https://issues.redhat.com/browse/MON-1162
- [x] update downstream backport of [openshift/kube-rbac-proxy](https://github.com/openshift/kube-rbac-proxy), v0.5.0 -> v0.6.0 https://github.com/openshift/kube-rbac-proxy/pull/24
- [X] update downstream backport of [openshift/k8s-prometheus-adapter](https://github.com/openshift/k8s-prometheus-adapter), no new version
- [x] update downstream backport of [openshift/grafana](https://github.com/openshift/grafana), v6.5.3 -> v7.1.0 https://github.com/openshift/grafana/pull/42

## Jsonnet dependencies

- [x] cut new release in [kubernetes-monitoring/kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin)
- [x] cut new release in [thanos-io/kube-thanos](https://github.com/thanos-io/kube-thanos)
- [x] cut new release in [coreos/kube-prometheus](https://github.com/coreos/kube-prometheus)
  - update dependencies before doing release

## Cluster Monitoring Operator

- [x] update and pin jsonnet dependencies in [jsonnet/jsonnetfile.json](https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/jsonnetfile.json).
  - example: https://github.com/openshift/cluster-monitoring-operator/blob/release-4.3/jsonnet/jsonnetfile.json
  - dependencies should be pinned to branches released in previous paragraph
- [x] update golang dependencies by modifying [go.mod](https://github.com/openshift/cluster-monitoring-operator/blob/master/go.mod) file.
  - client-go version update to v0.18.3, https://github.com/openshift/cluster-monitoring-operator/pull/851
  - other Go updates, #879 
  - most important are dependencies on prometheus-operator and kubernetes components

**Comment by lilic** [comment]
Think we need to add this to the checklist as well in the future https://github.com/openshift/cluster-monitoring-operator/pull/846

**Comment by lilic** [comment]
https://github.com/prometheus/prometheus/releases/tag/v2.20.0 is available

**Comment by s-urbaniak** [comment]
closing out as we have executed all tasks
